server:
  port: 8080
#  context-path: /demo

spring:
  application:
    name: spring yaml example
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update